
  CREATE TABLE "BI"."SHABVTMENU" 
   (	"B_CODROL" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"CODOPC" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"DESOPC" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CODVIS" VARCHAR2(1 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "BI"."SHABVTMENU"."B_CODROL" IS 'USUARIO ACCESO AL MENU';
 
   COMMENT ON COLUMN "BI"."SHABVTMENU"."CODOPC" IS 'NUMERO DE OPCION';
 
   COMMENT ON COLUMN "BI"."SHABVTMENU"."DESOPC" IS 'DESCRIPCION DE OPCION';
 
   COMMENT ON COLUMN "BI"."SHABVTMENU"."CODVIS" IS 'VISUALIZA 0, NO VISUALIZA 1';
 
   COMMENT ON TABLE "BI"."SHABVTMENU"  IS 'MENU';
 
