
  CREATE TABLE "BI"."SHALESION" 
   (	"CODIGO" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"DESCR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USRCRE" VARCHAR2(100 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(100 BYTE), 
	"FECACT" DATE, 
	 CONSTRAINT "SHALESION_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "BI"."SHALESION"."CODIGO" IS 'CODIGO DEL LISTADO DE LAS LESIONES';
 
   COMMENT ON COLUMN "BI"."SHALESION"."DESCR" IS 'DESCRIPCION DEL LISTADO DE LAS LESIONES';
 
