
  CREATE TABLE "BI"."SHABVT002" 
   (	"CODUSER" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"DESUSER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CLUSER" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"B_CODROL" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"MAIL" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE, 
	"SUCURSAL" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "BI"."SHABVT002"."CODUSER" IS 'CODIGO DE USUARIO';
 
   COMMENT ON COLUMN "BI"."SHABVT002"."DESUSER" IS 'NOMBRE DE USUARIO';
 
   COMMENT ON COLUMN "BI"."SHABVT002"."CLUSER" IS 'CLAVE DE USUARIO';
 
   COMMENT ON COLUMN "BI"."SHABVT002"."B_CODROL" IS 'CODIGO DEL ROL';
 
   COMMENT ON COLUMN "BI"."SHABVT002"."MAIL" IS 'CORREO ELECTRONICO';
 
   COMMENT ON COLUMN "BI"."SHABVT002"."USRCRE" IS 'USUARIO DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "BI"."SHABVT002"."FECCRE" IS 'FECHA DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "BI"."SHABVT002"."USRACT" IS 'USUARIO QUE ACTUALIZ? EL REGISTRO';
 
   COMMENT ON COLUMN "BI"."SHABVT002"."FECACT" IS 'FECHA DE ACTUALIZACION DE REGISTRO';
 
   COMMENT ON TABLE "BI"."SHABVT002"  IS 'USUARIOS';
 
