
  CREATE TABLE "BI"."SHAMETAS" 
   (	"ANIO" NUMBER NOT NULL ENABLE, 
	"MES" NUMBER NOT NULL ENABLE, 
	"NUMTRABAJADOR" NUMBER NOT NULL ENABLE, 
	"SUCURSAL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"HEADCOUNT" NUMBER NOT NULL ENABLE, 
	"PROMEDIO" FLOAT(126) NOT NULL ENABLE, 
	"REUNIONES" NUMBER, 
	"CUMPLIMIENTO" NUMBER NOT NULL ENABLE, 
	"USRCRE" VARCHAR2(100 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(100 BYTE), 
	"FECACT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 
