
  CREATE TABLE "BI"."SHAINCIDENCIAS" 
   (	"CI" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"GENERO" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"CARGO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"FECHA" DATE NOT NULL ENABLE, 
	"TURNO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"AREAEVENT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"TIPOINCAP" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"TIPOACC" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"TIPOLES" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"UBILES" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCHEC" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"INPSASEL" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"USRCRE" VARCHAR2(100 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(100 BYTE), 
	"FECACT" DATE, 
	"REGIST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."CI" IS 'CEDULA DE IDENTIDAD';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."NOMBRE" IS 'NOMBRE COMPLETO';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."GENERO" IS 'GENERO DEL EMPLEADO';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."CARGO" IS 'CARGO DEL EMPLEADO';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."FECHA" IS 'FECHA Y HORA DEL EVENTO';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."TURNO" IS 'TURNO';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."AREAEVENT" IS 'AREA DONDE OCURRIO EL EVENTO';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."TIPOINCAP" IS 'TIPO DE INCAPACIDAD';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."TIPOACC" IS 'TIPO DE ACCIDENTE';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."TIPOLES" IS 'TIPO DE LESION';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."UBILES" IS 'UBICACION DE LA LESION EN EL CUERPO';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."DESCHEC" IS 'DESCRIPCION DE LOS HECHOS';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."INPSASEL" IS 'CODIGO INPSASEL';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."USRCRE" IS 'USUARIO QUE CREO EL REGISTRO';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."FECCRE" IS 'FECHA DE CREACION DEL REGISTRO';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."USRACT" IS 'USUARIO QUE ACTUALIZO EL REGISTRO';
 
   COMMENT ON COLUMN "BI"."SHAINCIDENCIAS"."FECACT" IS 'FECHA DE ACTUALIZACION DEL REGISTRO';
 

  CREATE OR REPLACE TRIGGER "BI"."SHAINCIDENCIAS_TRG" 
BEFORE INSERT ON SHAINCIDENCIAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.REGIST IS NULL THEN
      SELECT SHAINCIDENCIAS_SEQ.NEXTVAL INTO :NEW.REGIST FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BI"."SHAINCIDENCIAS_TRG" ENABLE;
 
